### ISSUE TITLE
Not possible to assign a different data type to the suggested Metadata data type

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf#229]
I would like to define this field as STRING but in the "TIPO" list just INT type is displayed.
ex: CODICEEDIFICIO: 0110270164 - this is a string 

Should I use "Tipo colonna" instead?

<img width="1028" alt="screen shot 2018-02-01 at 17 41 10" src="https://user-images.githubusercontent.com/1733135/35690990-a4e0243e-0777-11e8-816a-ee0d0f20075b.png">

**Comment by giux78** [comment]
@mariaclaudia lo abbiamo risolto ma testato poco, fai qualche prova e se passano i tuoi test chiudilo te. Se hai errori mandaci il file.

**Comment by giux78** [comment]
@mariaclaudia anche questo è front-end ma se lo riapri fallo li altrimenti chiudi questo.

**Comment by mariaclaudia** [comment]
ok, done.
