### ISSUE TITLE
Data getting truncated uploading dataset from daf to kylo - Nifi polling

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf#232]
Daf - Kylo -  Nifi is polling every 10 sec 
I uploaded a file of 46 MB - 00:31 sec to be uploaded -> the dataset was truncated.
The Nifi time-slot has to be increased.

**Comment by panelladavide** [comment]
I set the "minimum file age" property to "5 sec" in the "GetFile" Nifi Processor which avoids the file truncation, during the ingestion flows.
