### ISSUE TITLE
Errore durante il caricamento di un nuovo dataset su Dataportal

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf#238]
Viene visualizzato il messaggio di errore "Errore durante il caricamento. Si prega di riprovare più tardi." caricando un sample di dati in formato csv.
Lo stesso sample se caricato direttamente su un feed Kylo funziona correttamente presumibilmente il problema è su dataportal e non sull'inferenza dei dati.

**Comment by mariaclaudia** [comment]
<img width="1029" alt="screen shot 2018-02-19 at 16 08 49" src="https://user-images.githubusercontent.com/1733135/36384913-3c7c6f38-1591-11e8-8111-225f31cf7b66.png">

**Comment by giux78** [comment]
@mariaclaudia dobbiamo chiedere in stadup se fare in ita o ing ci sono anche stranieri. Lo chiudo manca il file di esempio.
