### ISSUE TITLE
 Modifica password utente non propagata ai componenti (Superset)

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf#239]
Quando viene forzata una nuova password legata ad un'utenza, le modifiche non vengono propagate sui vari componenti.
Nello screenshot allegato, l'utente accede a daf con la nuova password impostata dall'operatore ma non riesce ad accedere a Superset

<img width="973" alt="usererror" src="https://user-images.githubusercontent.com/1733135/36384708-83faf6c8-1590-11e8-9628-1bf83e8e36f1.png">

**Comment by giux78** [comment]
utente cancellato e ri-registrato ma con stessa mail. Necessita cancellare anche da superset e ri-registrare. Abbiamo un task di pulizia delle utenze su jira
