### ISSUE TITLE
Hard-coded  - data aggiornamento nei miei dataset.

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf#244]
La data ultimo aggiornamento presente sui dataset caricati è hard-coded per tutti: 2017-07-23
<img width="880" alt="screen shot 2018-02-19 at 16 36 38" src="https://user-images.githubusercontent.com/1733135/36385600-3c643f88-1593-11e8-9734-a66ad36543ad.png">

**Comment by giux78** [comment]
@mariaclaudia  to open in daf-dataportal

**Comment by mariaclaudia** [comment]
ok, done https://github.com/italia/daf-dataportal/issues/160
