### ISSUE TITLE
Error while loading dataset into Jupyter

### ISSUE THREAD

**Issue by rajeevtommandru** [italia/daf#245]
![capture](https://user-images.githubusercontent.com/20303543/36421048-0e14dca8-165d-11e8-8b01-8bb6c1d42496.JPG)
I am facing a problem when I try reading data into JuPyteR notebook with PySpark3 Kernel

**Comment by panelladavide** [comment]
The path does not exist, try with this path: "/daf/ordinary/default_org/EDUC__eventi/default_org_o_anagrafe_biblioteche_nazionali_info_territoriali"

**Comment by rajeevtommandru** [comment]
This happened with some other data sets too!How to tame them

**Comment by rajeevtommandru** [comment]
![capture](https://user-images.githubusercontent.com/20303543/36423482-23f368c4-1666-11e8-87cc-2a6832e520fa.JPG)
Now I have this issue, mentioning that schema should be specified manually can't be inferred

**Comment by panelladavide** [comment]
![image](https://user-images.githubusercontent.com/14333567/36424664-6aca8632-1644-11e8-8dea-1507a2a83533.png)

No files in that path.

**Comment by rajeevtommandru** [comment]
Okay I'll work on other data set and let you know outcome

**Comment by rajeevtommandru** [comment]
It's working for other data set. Thankyou @panelladavide let's close the issue
